if(NOT DEFINED ENCODER_CORE OR NOT DEFINED GROUPA_TABLES)
  message(FATAL_ERROR "ENCODER_CORE and GROUPA_TABLES are required")
endif()
file(READ "${ENCODER_CORE}" CORE)
get_filename_component(_encdir "${ENCODER_CORE}" DIRECTORY)
file(GLOB _encparts "${_encdir}/encoder_*.cpp" "${_encdir}/encoder_internal.h")
foreach(_part IN LISTS _encparts)
  file(READ "${_part}" _part_text)
  string(APPEND CORE "\n${_part_text}")
endforeach()
file(READ "${GROUPA_TABLES}" TABLES)
function(require_text HAYSTACK NEEDLE LABEL)
  string(FIND "${${HAYSTACK}}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "missing Group-A entropy feature: ${LABEL}")
  endif()
endfunction()
require_text(CORE "choose_bitplane(" "compressed bitplane selection")
require_text(CORE "encode_norm2_bits(" "NORM2 bitplanes")
require_text(CORE "encode_norm6_bits(" "NORM6 bitplanes")
require_text(CORE "encode_rowskip_bits(" "ROWSKIP bitplanes")
require_text(CORE "encode_colskip_bits(" "COLSKIP bitplanes")
require_text(CORE "choose_mv_table(" "adaptive MVTAB")
require_text(CORE "choose_cbp_table(" "adaptive CBPTAB")
require_text(CORE "choose_inter_ac_index(" "adaptive inter AC sets")
require_text(CORE "dc_table_index" "adaptive DCTABLE")
require_text(CORE "kHighRateIntra" "low-Q High Rate intra AC table availability")
require_text(CORE "score_pair(yi,ci)" "auto AC-table scoring across legal luma/chroma sets")
require_text(TABLES "kNorm6Codes" "NORM6 VLC table")
require_text(TABLES "kMvDiffCodes" "MVDATA VLC tables")
require_text(TABLES "kPcbpCodes" "CBPCY VLC tables")
require_text(TABLES "kDcVlc" "DC VLC tables")
