file(READ "${SRC}/include/libvc1.h" H)
file(READ "${SRC}/src/encoder_core.cpp" C)
file(GLOB _encparts "${SRC}/src/encoder_*.cpp" "${SRC}/src/encoder_internal.h")
foreach(_part IN LISTS _encparts)
  file(READ "${_part}" _part_text)
  string(APPEND C "\n${_part_text}")
endforeach()
file(READ "${SRC}/src/frontend.cpp" F)
file(READ "${SRC}/tests/smoke.sh" S)
string(REGEX MATCH "#define[ \t]+LIBVC1_API_VERSION[ \t]+([0-9]+)" API_VERSION_MATCH "${H}")
if(NOT API_VERSION_MATCH)
  message(FATAL_ERROR "rate-control cleanup public API version marker missing")
endif()
if(CMAKE_MATCH_1 LESS 11)
  message(FATAL_ERROR "rate-control cleanup requires public API version >= 11; found ${CMAKE_MATCH_1}")
endif()
string(FIND "${H}" "b_predictor_rc" stale_predictor_api_pos)
string(FIND "${H}" "b_old_rc" stale_old_api_pos)
string(FIND "${H}" "f_i_share" stale_share_api_pos)
if(NOT stale_predictor_api_pos EQUAL -1 OR NOT stale_old_api_pos EQUAL -1 OR NOT stale_share_api_pos EQUAL -1)
  message(FATAL_ERROR "removed rate-control compatibility fields remain in public API")
endif()
if(NOT C MATCHES "struct AbrRateControl")
  message(FATAL_ERROR "ABR one-pass RC implementation missing")
endif()
string(FIND "${H}" "f_rc_i_weight" i_weight_api_pos)
string(FIND "${H}" "f_rc_p_weight" p_weight_api_pos)
string(FIND "${H}" "f_rc_b_weight" b_weight_api_pos)
string(FIND "${C}" "i_weight=5.0" i_weight_default_pos)
string(FIND "${C}" "p_weight=1.0" p_weight_default_pos)
string(FIND "${C}" "b_weight=0.70" b_weight_default_pos)
string(FIND "${C}" "gop_weight_total_estimate" weight_total_pos)
string(FIND "${C}" "announce_picture_block_weight" block_announce_pos)
string(FIND "${C}" "picture_intra_mbs" block_mix_pos)
string(FIND "${C}" "rate_weighted_mquant" block_mquant_pos)
string(FIND "${C}" "rc_intra_block_weight" block_i_weight_pos)
string(FIND "${C}" "rc_inter_block_weight" block_inter_weight_pos)
if(i_weight_api_pos EQUAL -1 OR p_weight_api_pos EQUAL -1 OR b_weight_api_pos EQUAL -1 OR
   i_weight_default_pos EQUAL -1 OR p_weight_default_pos EQUAL -1 OR b_weight_default_pos EQUAL -1 OR
   weight_total_pos EQUAL -1 OR block_announce_pos EQUAL -1 OR block_mix_pos EQUAL -1 OR
   block_mquant_pos EQUAL -1 OR block_i_weight_pos EQUAL -1 OR block_inter_weight_pos EQUAL -1)
  message(FATAL_ERROR "configurable normalized I/P/B macroblock-class ABR weight model missing")
endif()
if(NOT C MATCHES "short_term_cplxsum\\*=0\\.5")
  message(FATAL_ERROR "blurred-complexity state missing")
endif()
if(NOT C MATCHES "cplxr_sum")
  message(FATAL_ERROR "running rate-factor state missing")
endif()
if(NOT C MATCHES "kIpFactor=1\\.40" OR NOT C MATCHES "kPbFactor=1\\.30")
  message(FATAL_ERROR "ABR I/P or P/B reference factor missing")
endif()
if(NOT C MATCHES "reference_qscale=std::sqrt\\(previous_non_b_qscale\\*last_non_b_qscale\\)")
  message(FATAL_ERROR "B-picture surrounding-anchor qscale protection missing")
endif()
string(FIND "${C}" "candidate_q>reference_q+10" gap_guard_pos)
string(FIND "${C}" "candidate_q-6" gap_step_pos)
string(FIND "${C}" "repaired_bits<=repair_budget" gap_budget_pos)
if(gap_guard_pos EQUAL -1 OR gap_step_pos EQUAL -1 OR gap_budget_pos EQUAL -1)
  message(FATAL_ERROR "pathological B/reference quality-gap repair missing")
endif()

string(FIND "${C}" "b_quality_factor=kPbFactor-0.30*hard" b_adapt_factor_pos)
string(FIND "${C}" "b_debt_strength=1.35-0.80*hard" b_adapt_debt_pos)
string(FIND "${C}" "const double b_floor=b_plan*0.55" b_floor_pos)
string(FIND "${C}" "const double cliff_reference=std::max(decision.planned_bits,decision.target_bits)" b_cliff_reference_pos)
string(FIND "${C}" "actual<cliff_reference*0.20" b_cliff_pos)
if(b_adapt_factor_pos EQUAL -1 OR b_adapt_debt_pos EQUAL -1 OR b_floor_pos EQUAL -1 OR b_cliff_reference_pos EQUAL -1 OR b_cliff_pos EQUAL -1)
  message(FATAL_ERROR "residual-aware B-picture rate-allocation repair missing")
endif()

string(FIND "${S}" "refq=scale_to_q(math.sqrt(q_to_scale(past[-1])*q_to_scale(future[0])))" smoke_midpoint_pos)
string(FIND "${S}" "if bq < max(past[-1],future[0])" stale_anchor_max_pos)
if(smoke_midpoint_pos EQUAL -1 OR NOT stale_anchor_max_pos EQUAL -1)
  message(FATAL_ERROR "historical B/reference smoke test does not match geometric qscale invariant")
endif()

if(NOT C MATCHES "Independent GOP workers cannot share a fully sequential ABR rate factor")
  message(FATAL_ERROR "GOP-local budget-closure correction missing")
endif()

if(NOT C MATCHES "planned_bits_sum")
  message(FATAL_ERROR "type-weighted GOP spend ledger missing")
endif()
if(NOT C MATCHES "post_i_credit_bits")
  message(FATAL_ERROR "unused I-share carry-forward state missing")
endif()
string(FIND "${C}" "repair_target=picture_plan+post_i_credit_bits" post_i_repair_pos)
if(post_i_repair_pos EQUAL -1)
  message(FATAL_ERROR "first-P post-I budget repair missing")
endif()
if(NOT C MATCHES "previous_non_b_kind==GopPictureKind::I" OR NOT C MATCHES "normal_b_bits<=b_affordable")
  message(FATAL_ERROR "predictor-gated first-B-group coarseness guard missing")
endif()
if(NOT C MATCHES "pred\\[0\\]\\.coeff=0\\.19" OR NOT C MATCHES "pred\\[1\\]\\.coeff=0\\.23" OR NOT C MATCHES "pred\\[2\\]\\.coeff=0\\.23")
  message(FATAL_ERROR "calibrated coded-size predictor seeds missing")
endif()
string(FIND "${C}" "const int ss=1;" full_i_activity_pos)
string(FIND "${C}" "actual>decision.planned_bits*1.35" i_overspend_guard_pos)
string(FIND "${C}" "repair_target=decision.planned_bits*1.20" i_overspend_target_pos)
if(full_i_activity_pos EQUAL -1 OR i_overspend_guard_pos EQUAL -1 OR i_overspend_target_pos EQUAL -1)
  message(FATAL_ERROR "high-resolution I activity / GOP-opening overspend repair missing")
endif()
string(FIND "${S}" "i_overspend_retry=(x['type']=='I'" smoke_i_retry_pos)
string(FIND "${S}" "first<allowed*0.95" smoke_i_nonvbv_pos)
if(smoke_i_retry_pos EQUAL -1 OR smoke_i_nonvbv_pos EQUAL -1)
  message(FATAL_ERROR "historical severe smoke test does not recognize bounded non-VBV I overspend repair")
endif()
string(FIND "${C}" "const PAnalysis local=analyze_p_picture_core(f,ref,ProgressiveMvMode::OneMvQpel,false,nullptr);" zoom_local_pos)
string(FIND "${C}" "lm<c_.scene_threshold*0.86" zoom_threshold_pos)
string(FIND "${C}" "az>=0.005L && az<=0.08L" zoom_slope_pos)
if(zoom_local_pos EQUAL -1 OR zoom_threshold_pos EQUAL -1 OR zoom_slope_pos EQUAL -1)
  message(FATAL_ERROR "zoom-aware scene-cut local-motion rescue missing")
endif()
string(FIND "${C}" "const bool bounded_cq=p.i_rc_method==VC1_RC_ABR" abr_default_pos)
string(FIND "${C}" "struct RcPicturePredictor" stale_predictor_core_pos)
string(FIND "${C}" "GopBudgetExceeded" stale_old_budget_pos)
string(FIND "${F}" "--predictor-rc" stale_predictor_cli_pos)
string(FIND "${F}" "--old-rc" stale_old_cli_pos)
string(FIND "${F}" "--i-share" stale_share_cli_pos)
if(abr_default_pos EQUAL -1)
  message(FATAL_ERROR "ABR RC is not the sole ABR mode")
endif()
if(NOT stale_predictor_core_pos EQUAL -1 OR NOT stale_old_budget_pos EQUAL -1 OR NOT stale_predictor_cli_pos EQUAL -1 OR NOT stale_old_cli_pos EQUAL -1 OR NOT stale_share_cli_pos EQUAL -1)
  message(FATAL_ERROR "obsolete rate-control implementation or CLI remains")
endif()

string(FIND "${C}" "estimate_modern_gop_difficulty" modern_la_estimator_pos)
string(FIND "${C}" "kModernLookaheadGops=3" modern_la_window_pos)
string(FIND "${C}" "modern_budget_scale" modern_la_scale_pos)
string(FIND "${C}" "effective_target_per_frame()" modern_la_target_pos)
string(FIND "${C}" "modern_lookahead_credit_bits" modern_la_credit_pos)
string(FIND "${C}" "future_reserve_capacity" modern_la_capacity_pos)
string(FIND "${C}" "Sliding current+2-future ABR window" modern_la_sliding_pos)
if(modern_la_estimator_pos EQUAL -1 OR modern_la_window_pos EQUAL -1 OR modern_la_scale_pos EQUAL -1 OR modern_la_target_pos EQUAL -1 OR modern_la_credit_pos EQUAL -1 OR modern_la_capacity_pos EQUAL -1 OR modern_la_sliding_pos EQUAL -1)
  message(FATAL_ERROR "modern sliding three-GOP complexity lookahead/credit planner missing")
endif()
