if (NOT DEFINED SRC)
    message(FATAL_ERROR "SRC is required")
endif()
file(READ "${SRC}/tests/smoke.sh" smoke)
string(FIND "${smoke}" "--search-range 4 --keyint 24 2>\"$TMP/keyquality.log\"" cmd_pos)
if (cmd_pos EQUAL -1)
    message(FATAL_ERROR "periodic-I keyquality smoke fixture must explicitly request --keyint 24")
endif()
string(FIND "${smoke}" "keyint=24, gop-grid=scene-reset" summary_pos)
if (summary_pos EQUAL -1)
    message(FATAL_ERROR "periodic-I keyquality smoke fixture must verify keyint=24")
endif()
string(FIND "${smoke}" "--keyframe 1 --keyframe 25 --keyframe-min 50" quality_pos)
if (quality_pos EQUAL -1)
    message(FATAL_ERROR "periodic-I keyquality fixture must verify frames 1 and 25")
endif()
message(STATUS "periodic-I smoke fixture pins its historical 24-frame cadence")
