cmake_policy(SET CMP0007 NEW)

if(NOT DEFINED SRC)
  message(FATAL_ERROR "SRC required")
endif()
set(parts
  encoder_core.cpp encoder_api_helpers.cpp encoder_internal.h encoder_encode.cpp encoder_motion.cpp
  encoder_motion_compensation.cpp encoder_transform.cpp encoder_aq.cpp
  encoder_entropy.cpp encoder_filter.cpp encoder_compute.cpp encoder_simd.cpp encoder_rate_control.cpp encoder_bitstream.cpp)
foreach(part IN LISTS parts)
  if(NOT EXISTS "${SRC}/src/${part}")
    message(FATAL_ERROR "missing encoder subsystem file: ${part}")
  endif()
endforeach()
file(STRINGS "${SRC}/src/encoder_core.cpp" core_lines)
list(LENGTH core_lines nlines)
if(nlines GREATER 3500)
  message(FATAL_ERROR "encoder_core.cpp grew back to ${nlines} lines; keep it as the coordinator")
endif()
message(STATUS "encoder subsystem split ok; encoder_core.cpp ${nlines} lines")

# x86 SIMD dispatch must remain feature-flag based.  In particular, FMA4 must
# never be inferred from a CPU vendor/name/model because original Zen hides the
# flag and later Zen/Intel CPUs do not provide the supported FMA4 target.
file(READ "${SRC}/src/encoder_simd.cpp" simd_source)
string(FIND "${simd_source}" "__builtin_cpu_is" cpu_is_pos)
if(NOT cpu_is_pos EQUAL -1)
  message(FATAL_ERROR "SIMD dispatch must not use __builtin_cpu_is/vendor-model detection")
endif()
string(FIND "${simd_source}" "/proc/cpuinfo" cpuinfo_pos)
if(NOT cpuinfo_pos EQUAL -1)
  message(FATAL_ERROR "SIMD dispatch must not parse /proc/cpuinfo names/models")
endif()
string(REGEX MATCHALL "__builtin_cpu_supports\\(\"fma4\"\\)" fma4_checks "${simd_source}")
list(LENGTH fma4_checks fma4_count)
if(fma4_count LESS 2)
  message(FATAL_ERROR "Bulldozer and Piledriver must each be hard-gated by the CPUID FMA4 feature flag")
endif()
message(STATUS "SIMD dispatch uses feature flags; FMA4 has ${fma4_count} explicit CPUID gates")

# qemu-user SIMD test support must remain opt-in and target-constrained.
foreach(qemu_test_file run_simd_isa_test.py simd_emulated_cpu_probe.cpp simd_qemu_runner_selftest.py)
  if(NOT EXISTS "${SRC}/tests/${qemu_test_file}")
    message(FATAL_ERROR "missing QEMU SIMD test support file: ${qemu_test_file}")
  endif()
endforeach()
file(READ "${SRC}/CMakeLists.txt" cmake_source)
string(FIND "${cmake_source}" "set(LIBVC1_SIMD_TEST_MODE \"native\"" qemu_default_native)
if(qemu_default_native EQUAL -1)
  message(FATAL_ERROR "SIMD test execution must default to native mode")
endif()
file(READ "${SRC}/tests/run_simd_isa_test.py" qemu_runner)
foreach(required_text "Opteron_G4" "Opteron_G5" "xop=on" "fma4=on" "Nehalem" "Haswell" "Skylake-Server" "avx2-partial")
  string(FIND "${qemu_runner}" "${required_text}" required_pos)
  if(required_pos EQUAL -1)
    message(FATAL_ERROR "QEMU SIMD runner lost required target constraint: ${required_text}")
  endif()
endforeach()
message(STATUS "QEMU SIMD test runner is opt-in, target-constrained, and FMA4-explicit")
