if (NOT DEFINED SRC)
    message(FATAL_ERROR "SRC is required")
endif()
file(STRINGS "${SRC}/VERSION" version LIMIT_COUNT 1)
if (NOT version MATCHES "^([0-9]+)\\.([0-9]+)\\.([0-9]+)$")
    message(FATAL_ERROR "invalid VERSION: ${version}")
endif()
set(major "${CMAKE_MATCH_1}")
set(minor "${CMAKE_MATCH_2}")
set(patch "${CMAKE_MATCH_3}")
file(READ "${SRC}/include/libvc1.h" header)
foreach(pair "MAJOR;${major}" "MINOR;${minor}" "PATCH;${patch}")
    list(GET pair 0 key)
    list(GET pair 1 val)
    if (NOT header MATCHES "#define LIBVC1_VERSION_${key} +${val}([^0-9]|$)")
        message(FATAL_ERROR "libvc1.h ${key} does not match VERSION=${version}")
    endif()
endforeach()
if (NOT header MATCHES "#define LIBVC1_VERSION_STRING +\\\"${version}\\\"")
    message(FATAL_ERROR "LIBVC1_VERSION_STRING does not match VERSION=${version}")
endif()
file(READ "${SRC}/CMakeLists.txt" cmake)
if (NOT cmake MATCHES "file\\(STRINGS +\\\"\\$\\{CMAKE_CURRENT_SOURCE_DIR\\}/VERSION\\\"")
    message(FATAL_ERROR "CMake must derive project version from VERSION")
endif()
file(READ "${SRC}/flake.nix" flake)
if (flake MATCHES "version += +\\\"[0-9]+\\.[0-9]+\\.[0-9]+\\\"")
    message(FATAL_ERROR "flake.nix must not hard-code the package version")
endif()
if (NOT flake MATCHES "builtins\\.readFile +\\./VERSION" OR NOT flake MATCHES "version += +libvc1Version")
    message(FATAL_ERROR "flake.nix must derive package version from VERSION")
endif()
file(READ "${SRC}/src/matroska_muxer.cpp" mkv)
if (NOT mkv MATCHES "LIBVC1_VERSION_STRING")
    message(FATAL_ERROR "Matroska WritingApp metadata must use LIBVC1_VERSION_STRING")
endif()
message(STATUS "release version metadata is consistent: ${version}")
